### ISSUE TITLE
Instructions for Running in README

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#17]
Need to include instructions in the README for running the application.

**Comment by ryanleesipes** [comment]
@bflanagin in the most recent commit everything looks great https://github.com/LeafletBomb/leafletbomb/commit/fb1f6528fd17742e46ba6d7aeb2098ea670e8c26

One problem, however, is that after installing mongodb (which is necessary), it seems as though it is still complaining.

```
[[[[[ ~/Projects/leafletbomb ]]]]]

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/lib/node_modules/meteor/mongodb/bin/mongod ENOENT
    at _errnoException (util.js:1019:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

Any ideas as to what to do with this?

**Comment by ryanleesipes** [comment]
This looks really good @bflanagin - closing this issue. Thanks!
