### ISSUE TITLE
Error trying to start application

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#18]
Using node LTS and current version of Meteor.

```
/home/ryan/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.relative (path.js:496:3)
    at /home/ryan/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/static-assets/server/mini-files.js:109:14
    at ImportScanner._getRelativeImportId (/tools/isobuild/import-scanner.js:525:43)
    at /tools/isobuild/import-scanner.js:509:33
    at _.each._.forEach (/home/ryan/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._resolve (/tools/isobuild/import-scanner.js:498:7)
    at /tools/isobuild/import-scanner.js:564:29
    at _.each._.forEach (/home/ryan/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:557:5)
    at /tools/isobuild/import-scanner.js:670:12
    at _.each._.forEach (/home/ryan/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:557:5)
    at /tools/isobuild/import-scanner.js:670:12
    at _.each._.forEach (/home/ryan/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:557:5)
    at /tools/isobuild/import-scanner.js:670:12
    at _.each._.forEach (/home/ryan/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:557:5)
    at /tools/isobuild/import-scanner.js:670:12
    at _.each._.forEach (/home/ryan/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:557:5)
    at /tools/isobuild/import-scanner.js:357:14
    at Array.forEach (native)
    at ImportScanner.scanImports (/tools/isobuild/import-scanner.js:355:22)
    at /tools/isobuild/compiler-plugin.js:1040:17
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1008:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1059:8)
    at /tools/isobuild/bundler.js:830:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:821:18)
    at /tools/isobuild/bundler.js:2918:14
    at /tools/isobuild/bundler.js:3007:20
    at Array.forEach (native)
    at Function._.each._.forEach (/home/ryan/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:3006:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2899:31)
    at /tools/isobuild/bundler.js:2846:32
    at Object.withCache (/tools/fs/files.js:1694:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2846:16)
    at /tools/runners/run-app.js:583:36
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:582:34)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:626:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:885:28)
    at /tools/runners/run-app.js:412:12
```

**Comment by ryanleesipes** [comment]
Nevermind, did a git reset --hard and it works.
