### ISSUE TITLE
Recurring Error while Running

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#76]
No inkling as to what it means, seemingly has no effect on the application. But here is the error I'm seeing in the terminal:

```
I20171026-10:03:00.006(-6)? Exception in callback of async function: TypeError: Cannot read property '_id' of undefined
I20171026-10:03:00.007(-6)?     at checkScheduledPosts (server/scheduler.js:13:14)
I20171026-10:03:00.008(-6)?     at runWithEnvironment (packages/meteor.js:1188:24)
```

**Comment by bflanagin** [comment]
Ah, its in the scheduler, apparently I need to make it a bit smarter.

**Comment by bflanagin** [comment]
Fixed
